#https://github.com/VaslD/Podspecs.git
#https://github.com/cuilinhao/vapor_podspec
source "https://github.com/cuilinhao/vapor_podspec.git"
#source "git@git.nevint.com:ios_dd/niopodrepo.git"
source "https://cdn.cocoapods.org/"

platform :ios, "13.0"

use_frameworks!

target "Example" do
  pod "Kitura"#, :podspec => "./Kitura/Kitura.podspec"
#  pod "KituraContracts", :podspec => "./Kitura/KituraContracts.podspec"
#  pod "KituraLoggerAPI", :podspec => "./Kitura/KituraLoggerAPI.podspec"
#  pod "KituraNIO", :podspec => "./Kitura/KituraNIO.podspec"
#  pod "KituraNIOLinuxHelpers", :podspec => "./Kitura/KituraNIOLinuxHelpers.podspec"
#  pod "KituraTemplateEngine", :podspec => "./Kitura/KituraTemplateEngine.podspec"
#  pod "KituraTypeDecoder", :podspec => "./Kitura/KituraTypeDecoder.podspec"
#
#  pod "BlueSocket", :podspec => "./Kitura/BlueSocket.podspec"
#  pod "BlueSSLService", :podspec => "./Kitura/BlueSSLService.podspec"
#
#  pod "HeliumLogger", :podspec => "./Kitura/HeliumLogger.podspec"
#
  pod 'GCDWebServer'
#  //git@github.com:VaslD/Podspecs.git

#pod "Vapor"
pod "Vapor", :testsec => ["VaporTests"]
  
end

post_install do |installer|
  installer.pods_project.targets.each do |target|
    target.build_configurations.each do |config|
      if target.respond_to?(:product_type) and target.product_type == "com.apple.product-type.bundle"
        config.build_settings["CODE_SIGNING_ALLOWED"] = "NO"
      end
    end
  end
end
